### PR TITLE
_encode_input_for_recaptcha: catch unicode errors caused by non-ascii

### PR DESCRIPTION
**Pull request by starius**
Before this, django-recaptcha-field caused errors if user entered non-ascii
symbols in the solution.

### CODE REVIEW

**Comment by gnarea** [comment]
Can you please provide the following?
- Traceback.
- The problematic string.
- The chartset used in your Django project.

Without this information, it's hard to tell whether the bug is in this library, the reCAPTCHA library or your code.

**Comment by starius** [comment]
- абвгд
- DEFAULT_CHARSET 'utf-8'
- Traceback:

File "/project/lib/python2.7/django/core/handlers/base.py" in get_response
115.                         response = callback(request, _callback_args, *_callback_kwargs)
File "/project/myproject/myproject/views.py" in user_register_view
456.         if form.is_valid():
File "/project/lib/python2.7/django/forms/forms.py" in is_valid
126.         return self.is_bound and not bool(self.errors)
File "/project/lib/python2.7/django/forms/forms.py" in _get_errors
117.             self.full_clean()
File "/project/lib/python2.7/django/forms/forms.py" in full_clean
272.         self._clean_fields()
File "/project/lib/python2.7/django/forms/forms.py" in _clean_fields
287.                     value = field.clean(value)
File "/project/lib/python2.7/django/forms/fields.py" in clean
155.         self.validate(value)
File "/project/myproject/myproject/django_recaptcha_field.py" in validate
89.         solution_text = _encode_input_for_recaptcha(value['solution_text'])
File "/project/myproject/myproject/django_recaptcha_field.py" in _encode_input_for_recaptcha
142.         string_bytes = string.decode(settings.DEFAULT_CHARSET)
File "/usr/local/lib/python2.7/encodings/utf_8.py" in decode
16.     return codecs.utf_8_decode(input, errors, True)

Exception Type: UnicodeEncodeError at /register/
Exception Value: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)

**Comment by starius** [comment]
Recaptcha seems to use ascii symbols only. So we can consider any non-ascii solution wrong.

**Comment by gnarea** [comment]
Thanks for the extra info! I can indeed reproduce this bug, but I don't think we can apply the patch provided as is since there are no tests for it, it's not PEP-8 compliant and I think it's partially replicating something done in the python-recaptcha lib.

I've added an entry in our internal issue tracking system, so that we can solve it when we get a chance.

**Pull request closed without merging**
